name: Elixir CI

on:
  push:
    branches: [ CI_TEST, master ]
  pull_request:
    branches: [ CI_TEST, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./bubblit
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.9.4 # Define the elixir version [required]
        otp-version: 22.2 # Define the OTP version [required]
        
    - name: Install Dependencies
      run: mix deps.get |
            echo "deps.get"
      working-directory: ${{env.working-directory}}
    - name: Install npm Dependencies
      run: npm install |
          echo "npm install"
      working-directory: ${{env.working-directory}}
    - name: Run Tests
      run: mix test |
          echo "mix test"
      working-directory: ${{env.working-directory}}
