name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: move to program directory
      run: cd bubblit
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.9.4 # Define the elixir version [required]
        otp-version: 22.2 # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get |
            echo "deps.get"
    - name: Install npm Dependencies
      run: npm install |
          echo "npm install"
    - name: Run Tests
      run: mix test |
          echo "mix test"
